---
$schema: "https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json"
version: "0.2"
language: en
allowCompoundWords: true
ignorePaths:
  - "_build/*"
  - ".git/*"
  - "assets/vendor/*"
  - "cspell.config.yml"
  - "deps/*"
  - "erl_crash.dump"
  - "priv/static/assets/*"
words:
  - aria-describedby
  - aria-labelledby
  - behaviour
  - dedup
  - Ecto
  - esbuild
  - flyctl
  - heex
  - hexpm
  - httpc
  - httpoison
  - hspacer
  - libncurses
  - libstdc
  - msgid
  - myclass
  - myhook
  - mylist
  - nocase
  - noreply
  - rsquo
  - sarduty
  - SARVAC
  - signup
  - SRVTC
  - strftime
  - tbody
  - thead
  - totp
  - Tzdata
  - X
  - Zepto
