# https://mise.jdx.dev/configuration.html
#
# Copy to .mise.local.toml and edit with actual secrets

[env]
MAPBOX_ACCESS_TOKEN = "pk.e---"
TEAM_LOGO_PATH = "/Users/gerry/Developer/sarduty.mount/team-logos"
