# fly.toml app configuration file generated for sarduty on 2023-12-02T18:46:18-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sarduty"
primary_region = "yyz"
kill_signal = "SIGTERM"

[build]

[env]
DATABASE_PATH = "/mnt/sarduty/sarduty.db"
PHX_HOST = "sarduty.fly.dev"
PORT = "8080"
MAILGUN_DOMAIN = "mg.sarduty.com"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
[http_service.concurrency]
type = "connections"
hard_limit = 1000
soft_limit = 1000

[mounts]
source = "sarduty"
destination = "/mnt/sarduty"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
